### ISSUE TITLE
Also provide a version for GitHub Dark Theme

### ISSUE THREAD

**Issue by ghost** [Richienb/Richienb#2]

**Comment by Richienb** [comment]
At the moment, it is only possible to detect OS dark mode which is already implemented. Is there a way to detect if the website is dark mode?

**Comment by AaronDewes** [comment]
@Richienb GitHub seems to set `data-color-mode="dark"` on the root element (`<html>`) in dark mode

**Comment by Richienb** [comment]
I don't think it is possible to detect that class since it is outside of the svg element.

**Comment by Richienb** [comment]
https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/

https://github.com/Richienb/Richienb/commit/e68524a51bf6fc24b86f81f7bf5c62cb5dc115b2
